DeathEaters/DeathEaters/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home.as_view(),name = 'home'),
    path('loginPage/',views.Login.as_view(),name = 'Login'),
    path('logoutPage/',views.Logout.as_view(),name= 'Logout'),
    path('surveyor/', include('surveyor.urls', namespace='surveyor')),
    path('analyst/', include('analyst.urls', namespace='analyst')),
]

DeathEaters/analyst/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'analyst'

urlpatterns = [
    path('analystPage/', views.analystPage.as_view(),name = 'analystPage'),
    path('houseListQueries', views.houseListQueries.as_view(),name = 'houseListQueries'),
    path('houseHoldQueries', views.houseHoldQueries.as_view(),name = 'houseHoldQueries'),
    path('houseListQueryResult', views.houseListQueryResult.as_view(),name = 'houseListQueryResult'),
    path('houseHoldQueryResult', views.houseHoldQueryResult.as_view(),name = 'houseHoldQueryResult'),
]

DeathEaters/surveyor/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'surveyor'

urlpatterns = [
    path('surveyorPage', views.surveyorPage.as_view(),name = 'surveyorPage'),
    path('houselisting/',views.houselisting.as_view(),name ='houselisting'),
    path('households/',views.households.as_view(),name='households'),
]

DeathEaters/DeathEaters/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone
import datetime
from django.core.validators import MaxValueValidator
from django.db.models import OneToOneField

class HouseHolds(models.Model):
    
    SEX_CHOICES = (
        ('F', 'Female',),
        ('M', 'Male',),
        ('O', 'Other',),
    )

    CASTE_CHOICES = (
        ('SC', 'Scheduled-Caste',),
        ('ST', 'Scheduled-Tribe',),
        ('NA', 'None',),
    )

    MARITAL_STATUS_CHOICES = (
        ('1','Never-Married', ),
        ('2','Currently-Married', ),
        ('3','Widowed', ),
        ('4','Separated',),
        ('5','Divorced', ),
    )

    RELIGION_CHOICES = (
        ('H', 'Hindu',),
        ('M', 'Muslim',),
        ('C', 'Christian',),
        ('S', 'Sikh',),
        ('B', 'Buddhist',),
        ('J', 'Jain',),
    )

    DISABILITY_CHOICES = (
        ('1', 'Seeing',),
        ('2', 'Hearing',),
        ('3', 'Speech',),
        ('4', 'Movement',),
        ('5', 'Mental-Retardness',),
        ('6', 'Mental-Illness',),
        ('7', 'Multiple-Disability',),
        ('8', 'Other',),
    )

    QUALIFICATION_CHOICES = (
        ('1', 'School',),
        ('2', 'College',),
        ('3', 'Vocational',),
        ('4', 'Special Institution For Disabled',),
        ('5', 'Literacy-Centre',),
        ('6', 'Other-Institution',),
        ('7', 'None',),
    )

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    fname = models.CharField(default = 'AMAR', max_length=50)
    mname = models.CharField(default = 'AKBAR', max_length=50)
    lname = models.CharField(default = 'ANTHONY', max_length=50)
    state = models.CharField(default= 'UP',max_length=100)
    district = models.CharField(default='Pune',max_length=100)
    subDistrict = models.CharField(default='chincwad',max_length=100)
    village = models.CharField(default='chincwad',max_length=100)
    wardNo = models.IntegerField(default=0,max_length=100)
    adhar = models.BigIntegerField(max_length=12,primary_key=True) 
    sex = models.CharField(max_length=1,choices=SEX_CHOICES)
    dob = models.DateField(max_length=30) 
    age = models.IntegerField(max_length=4) 
    religion = models.CharField(max_length=1,choices=RELIGION_CHOICES)
    scst = models.CharField(max_length=2,choices=CASTE_CHOICES)
    scstType = models.CharField(default = 'KALA', max_length=50)
    martialStatus = models.CharField(max_length=1,choices=MARITAL_STATUS_CHOICES)
    disability = models.CharField(max_length=1,choices=DISABILITY_CHOICES)
    motherTongue =  models.CharField(default = 'Hindi', max_length=50)
    literate = models.BooleanField(default=True)
    statusOfAttendance = models.BooleanField(default=False)
    highestEDUAttained = models.CharField(max_length=1,choices=QUALIFICATION_CHOICES)

    CATEGORY_OF_WORKER = (
        ('1', 'Cultivator',),
        ('2', 'Agricultural-Labourer',),
        ('3', 'Work In household industry',),
        ('4', 'Other',),
    )

    CLASS_OF_WORKER = (
        ('1', 'Employer',),
        ('2', 'Employee',),
        ('3', 'Single-Worker',),
        ('4', 'Family-Worker',),
    )

    TYPE_OF_WORKER = (
        ('1', 'Main-Worker',),
        ('2', 'Marginal-Worker',),
        ('3', 'Non-Worker',),
    )

    TYPE_OF_NON_WORKER = (
        ('1', 'Student',),
        ('2', 'Household-Duties',),
        ('3', 'Dependent',),
        ('4', 'Pensioner',),
        ('5', 'Rentier',),
        ('6', 'Beggar',),
        ('7', 'Other',),
    )

    MODE_OF_TRAVEL = (
        ('1', 'On Foot',),
        ('2', 'Bicycle',),
        ('3', 'Moped/Scooter/Motor-Cycle',),
        ('4', 'Car/Jeep/VAN  ',),
        ('5', 'Literacy Centre',),
        ('6', 'Other Institution',),
        ('7', 'None',),
    )

    CAME_FROM = (
        ('1', 'Rural',),
        ('2', 'Urban',),
    )

    workedLike = models.CharField(max_length=1,choices= TYPE_OF_WORKER )
    workedAs =  models.CharField(max_length=1,choices= CLASS_OF_WORKER)
    describeWork = models.CharField(max_length=250)
    industryType = models.CharField(max_length=250)
    workerClass = models.CharField(max_length=1,choices=CLASS_OF_WORKER)
    nonWorkerType = models.CharField(max_length=1,choices=TYPE_OF_NON_WORKER)
    findingWork = models.BooleanField(default=False)
    disOfTravelInKm = models.FloatField(default=0.0)
    modeOfTravel = models.CharField(max_length=1,choices=MODE_OF_TRAVEL)
    birthPlace = models.CharField(max_length=500)
    # True => born in india 
    birthPlaceBool = models.BooleanField(default=True)
    placeOfLastResidence = models.CharField(max_length=500)
    # True => live in india 
    placeOfLastResidenceBool = models.BooleanField(default=True)
    lastMigrated = models.BooleanField(default=False)
    cameFrom = models.CharField(max_length=1,choices=CAME_FROM)
    durOfStayAfterMigration = models.IntegerField(default=1)
    curChildren = models.IntegerField(default=0)
    totChildren = models.IntegerField(default=1)
    



class HouseListing(models.Model):

    FLOOR_CHOICES = (
        ('1','Mud'),
        ('2','Wood/bamboo'),
        ('3','Burnt brick'),
        ('4','Stone'),
        ('5','Cement'),
        ('6','Mosaic/floor tiles'),
        ('7','Any other'),
    )

    WALL_CHOICES = (
        ('1','Grass/thatch/bamboo'),
        ('2','Plastic/polythene'),
        ('3','Mud/unburnt brick'),
        ('4','Wood'),
        ('5','Stone not packed with mortar'),
        ('6','Stone packed with mortar'),
        ('7','G.I./metal/asbestos sheets'),
        ('8','Burnt brick'),
        ('9','Concrete'),
        ('0','Any other'),
    )

    ROOF_CHOICES = (
        ('1','Grass/ thatch/ bamboo/ wood/ mud'),
        ('2','Plastic/ polythene'),
        ('3','Hand made tiles'),
        ('4','Machine made tiles'),
        ('5','Burnt brick'),
        ('6','Stone'),
        ('7','Slate'),
        ('8','G.I./metal/asbestos sheets'),
        ('9','Concrete'),
        ('0','Any other'),
    )

    USE_CHOICES = (
        ('1','Residence'),
        ('2','Residence-cum-other use'),
        ('3','Shop/ office'),
        ('4','School/ college'),
        ('5','Hotel/ lodge/ guest house'),
        ('6','Hospital/ dispensary'),
        ('7','Factory/ workshop/ workshed'),
        ('8','Place of worship'),
        ('9','Other non-residential use'),
        ('0','Any other'),
    )

    SEX_CHOICES = (
        ('F', 'Female',),
        ('M', 'Male',),
        ('O', 'Other',),
    )

    CASTE_CHOICES = (
        ('1','SC'),
        ('2','ST'),
        ('3','Other'),
    )

    OWNERSHIP_CHOICES = (
        ('1','Owned'),
        ('2','Rented but has own house elsewhere'),
        ('3','Rented and does not own any house'),
        ('4','Any other'),
    )

    DWATERAVAIL_CHOICES = (
        ('1','Within premises'),
        ('2','Near the premises'),
        ('3','Away'),
    )

    DWATERSOURCE_CHOICES = (
        ('1','Tap water from source'),
        ('2','Tap water from un-treated source'),
        ('3','Well'),
        ('4','Hand Pump'),
        ('5','Tubewell/ borehole'),
        ('6','Spring'),
        ('7','River/canal'),
        ('8','Tank/pond/lake'),
        ('9','Packaged/bottled water'),
        ('0','Other sources'),
    )

    LIGHTING_CHOICES = (
        ('1','Electricity'),
        ('2','Kerosene'),
        ('3','Solar'),
        ('4','Other oil'),
        ('5','Any other'),
        ('6','No lighting'),
    )

    LATRINEACCESS_CHOICES = (
        ('1','YES, Exclusively for household use only'),
        ('2','YES, Shared with other household'),
        ('3','YES, Public latrine'),
        ('4','NO, Open'),
    )

    LATRINETYPE_CHOICES = (
        ('1','Flush/pour flush latrine connected to Piped sewer system'),
        ('2','Flush/pour flush latrine connected to Septic tack'),
        ('3','Flush/pour flush latrine connected to Other system'),
        ('4','Twin Pit latrine With slab/ventilated improved pit'),
        ('5','Twin Pit latrine Without slab/open pit'),
        ('6','Single Pit latrine With slab/ventilated improved pit'),
        ('7','Single Pit latrine Without slab/open pit'),
        ('8','Service latrine Night soil removed by human'),
        ('9','Service latrine Night soil serviced by animals'),
        ('0','Night soil disposed into open drain'),
    )

    KITCHEN_CHOICES = (
        ('1','Cooking in kitchen, has LPG/PNG Connection'),
        ('2','Cooking in kitchen, Does not have LPG/PNG Connection'),
        ('3','Cooking inside house, but not in kitchen, Has LPG/PNG Connection'),
        ('4','Cooking inside house, but not in kitchen, does not have LPG/PNG Connection'),
        ('5','Cooking in open/ outside house, Has LPG/PNG Connection'),
        ('6','Cooking in open/ outside house, does not have LPG/PNG Connection'),
        ('7','No cooking'),
    )

    FUEL_CHOICES = (
        ('1','Firewood'),
        ('2','Crop residue'),
        ('3','Cowding cake'),
        ('4','Coal/lignite/charcoal'),
        ('5','Kerosene'),
        ('6','LPG/PNG'),
        ('7','Electricity'),
        ('8','Bio-gas'),
        ('9','Solar'),
        ('0','Any other'),
    )

    WASTEWATER_CHOICES = (
        ('1','Closed drainage'),
        ('2','Open drainage'),
        ('3','No drainage'),
    )

    BATHINGFACILITY_CHOICES = (
        ('1','YES, Bathroom'),
        ('2','YES, Enclosure without roof'),
        ('3','NO'),
    )

    RADIO_CHOICES = (
        ('1','YES, Traditional radio set'),
        ('2','YES, on mobile/smartphone'),
        ('3','YES, On any other device'),
        ('4','NO'),
    )

    TELEVISION_CHOICES = (
        ('1','YES, Doordarshan free dish'),
        ('2','YES, DTH/Dish'),
        ('3','YES, Cable connection'),
        ('4','Any other'),
        ('5','NO'),
    )

    INTERNET_CHOICES = (
        ('1','YES, On laptop/computer'),
        ('2','YES, On mobile/smartphone'),
        ('3','YES, On any other device'),
        ('4','NO'),
    )

    DEVICE_CHOICES = (
        ('1','YES'),

DeathEaters/DeathEaters/views.py
import os
from django.contrib.auth import authenticate, login, logout
from django.views import generic
from django.views.generic.base import View
from django.contrib.auth.models import Group
from django.contrib.auth.models import User
from django.urls import reverse_lazy
from django.shortcuts import render, redirect
from surveyor.models import HouseHolds 
from surveyor.models import HouseListing
from django.contrib.auth.hashers import make_password
from django.core.files.storage import FileSystemStorage
import shortuuid

class home(View):
    def get(self, request):
        return render(request, 'home.html')

class Login(View):
    def get(self, request, template_name='login.html'):
        return render(request,template_name)

    def post(self, request, template_name='login.html'):
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username,password=password)
        group = None
        if user is not None:
            if user.is_active:
                login(request, user)
                group = user.groups.all()[0].name
                if group == 'surveyor_group':
                    return redirect('surveyor:surveyorPage')
                if group == 'analyst_group':
                    return redirect('analyst:analystPage')
                else:
                    return render(request, 'home.html')
            else:
                return render(request, 'login.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'login.html', {'error_message': 'Invalid Login'})



class Logout(View):
    def get(self, request):
        logout(request)
        return render(request, 'home.html')
        


class analystPage(View):
    def get(self, request):
        return render(request, 'analystPage.html')

DeathEaters/DeathEaters/templates/analystPage.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
  <div class="page-header header-filter" data-parallax="true" style="background-image: url('/static/assets/img/temple.jpg')">
    <div class="container">
      <div class="row">
        <div class="col-md-6">
          <h1 class="title">Analyst Mode.</h1>
          <h4>Query for House Listings & House-Holds. For a household and per individual.</h4>
        </div>
      </div>
    </div>
  </div>
  <div class="main main-raised">
    <div class="container">
      <div class="section text-center">
        <div class="row">
          <div class="col-md-8 ml-auto mr-auto">
            <h2 class="title">Query Forms</h2>
            <h5 class="description">Query the House Holding and House Listing Forms of the Populus.</h5>
          </div>
        </div>
        <br><br>
        <div class="features">
          <div class="row">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-header card-header-icon card-header-rose">
                      <div class="card-icon">
                        <i class="material-icons">source</i>
                      </div>
                    </div>
                    <div class="card-body">
                        <h4 class="card-title">House Listing Queries</h4>
                            Query for every House of the Populus.
                    </div>
                    <br>
                    <div class="container">
                  <a href="{% url 'analyst:houseListQueries' %}" class="btn btn-rose">
                    Query House Listing 
                  </a></div>
                </div>
            </div>
            <div class="col-md-6">
              <div class="card">
                  <div class="card-header card-header-icon card-header-rose">
                    <div class="card-icon">
                      <i class="material-icons">
                        wysiwyg</i>
                    </div>
                  </div>
                  <div class="card-body">
                      <h4 class="card-title">House Hold Queries</h4>
                          Query for Individual Members data of the Populus.
                  </div>
                  <br>
                  <div class="container">
                  <a href="{% url 'analyst:houseHoldQueries' %}" class="btn btn-rose">
                    Query Open House Hold 
                  </a></div>
              </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  {% endblock %}

DeathEaters/DeathEaters/templates/base.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
<head>
  <meta charset="utf-8" />
  <link rel="apple-touch-icon" sizes="76x76" href="{% static 'assets/img/apple-icon.png' %}">
  <link rel="icon" type="image/png" href="{% static 'assets/img/favicon.png' %}">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.bundle.min.js" integrity="sha384-LtrjvnR4Twt/qOuYxE721u19sVFLVSA4hf/rRt6PrZTmiPltdZcI7q7PXQBYTKyf" crossorigin="anonymous"></script>
  <title>
    {% block title %}
            Census 2021
      {% endblock %}
  </title>
  <meta content='width=device-width, initial-scale=1.0, shrink-to-fit=no' name='viewport' />
  <!--     Fonts and icons     -->
  <link rel="stylesheet" type="text/css"
    href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">
  <!-- CSS Files -->
  <link href="{% static 'assets/css/material-kit.css' %}" rel="stylesheet" />
  <!-- CSS Just for demo purpose, don't include it in your project -->
  <link href="{% static 'assets/demo/demo.css' %}" rel="stylesheet" />
</head>

<body class="landing-page sidebar-collapse">
  <nav class="navbar navbar-transparent navbar-color-on-scroll fixed-top navbar-expand-lg" color-on-scroll="100"
    id="sectionsNav">
    <div class="container">
      <div class="navbar-translate">
        <a class="navbar-brand" href="{% url 'home' %}" >
          <span style="font-size:1.4rem">Census 2021</span></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" aria-expanded="false"
          aria-label="Toggle navigation">
          <span class="sr-only">Toggle navigation</span>
          <span class="navbar-toggler-icon"></span>
          <span class="navbar-toggler-icon"></span>
          <span class="navbar-toggler-icon"></span>
        </button>
      </div>
      <div class="collapse navbar-collapse">
        <ul class="navbar-nav ml-auto">
          <li class="dropdown nav-item">
            <a href="{% url 'surveyor:surveyorPage' %}" class="nav-link"><span style="font-size:1rem">Surveyor Page</span></a>
          </li>
          <li class="dropdown nav-item">
            <a href="{% url 'analyst:analystPage' %}" class="nav-link"><span style="font-size:1rem">Analyst Page</span></a>
          </li>
          {% if user.is_authenticated %}
          <li class="dropdown nav-item">
            <span style="font-size:1rem; text-transform:uppercase" class="nav-link">{{user.first_name}} {{user.last_name}}</span>
          </li>
          <li class="dropdown nav-item">
            <a href="{% url 'Logout' %}" class="nav-link"><span style="font-size:1rem">LOGOUT</span></a>
          </li>
          {% else %}
          <li class="dropdown nav-item">
            <a href="{% url 'Login' %}" class="nav-link"><span style="font-size:1rem">LOGIN</span></a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>

  {% block content %}

  {% endblock %}

  <footer class="footer footer-default">
    <div class="container">
      Made with 🖤 by Team VectorStatic of the Ingress Hackathon.
    </div>
  </footer>
  <!--   Core JS Files   -->
  <script src="{% static 'assets/js/core/jquery.min.js' %}" type="text/javascript"></script>
  <script src="{% static 'assets/js/core/popper.min.js' %}" type="text/javascript"></script>
  <script src="{% static 'assets/js/core/bootstrap-material-design.min.js' %}" type="text/javascript"></script>
  <script src="{% static 'assets/js/plugins/moment.min.js' %}"></script>
  <!--	Plugin for the Datepicker, full documentation here: https://github.com/Eonasdan/bootstrap-datetimepicker -->
  <script src="{% static 'assets/js/plugins/bootstrap-datetimepicker.js' %}" type="text/javascript"></script>
  <!--  Plugin for the Sliders, full documentation here: http://refreshless.com/nouislider/ -->
  <script src="{% static 'assets/js/plugins/nouislider.min.js' %}" type="text/javascript"></script>
  <!--  Google Maps Plugin    -->
  <!-- Control Center for Material Kit: parallax effects, scripts for the example pages etc -->
  <script src="{% static 'assets/js/material-kit.js' %}" type="text/javascript"></script>
</body>

</html>

DeathEaters/DeathEaters/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="page-header header-filter" data-parallax="true"
style="background-image: url('/static/assets/img/taj-mahal.jpg')">
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <h1 class="title">Office of the Registrar General & Census Commissioner, India.</h1>
      <h4>Office of the Registrar General & Census Commissioner, India</h4>
      <br>
      <a href="{% url 'Login' %}" class="btn btn-danger btn-raised btn-lg">
        Login
      </a>

    </div>
  </div>
</div>
</div>
<div class="main main-raised">
    <div class="container">
        <div class="section text-center">
            <div class="row">
                <div class="col-md-8 ml-auto mr-auto">
                    <h2 class="title">About </h2>
                    <h5 class="description">Every 10 Years, India performs a Census of more than a Billion people. Till the last Census, This was an Offline Paper-Filled Process. This is our attempt to make the process digitalised and truly define the New Normal in one of the country's biggest endeavours.
                    </h5>
                </div>
            </div>
        </div>
        <div class="section text-center container">
            <h2 class="title">Our team</h2>
            <div class="team">
                <div class="row">
                    <div class="col-md-4">
                        <div class="team-player">
                            <div class="card card-plain">
                                <div class="col-md-6 ml-auto mr-auto">
                                    <img src="{% static 'assets/img/faces/vaishnavi.jpg' %}" alt="Thumbnail Image"
                                        class="img-raised rounded-circle img-fluid">
                                </div>
                                <h4 class="card-title">Vaishnavi Mahajan
                                    <br>
                                    <small class="card-description text-muted">Full-Stack Web Developer</small>
                                </h4>
                                <div class="card-body">
                                    <p class="card-description">Any sufficiently advanced technology is equivalent to magic.</p>
                                </div>
                                <div class="card-footer justify-content-center">
                                    <a href="https://www.instagram.com/_vibhaa._/" target='_blank' class="btn btn-link btn-just-icon"><i
                                            class="fa fa-instagram"></i></a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="team-player">
                            <div class="card card-plain">
                                <div class="col-md-6 ml-auto mr-auto">
                                    <img src="{% static 'assets/img/faces/kajal.jpg' %}" alt="Thumbnail Image"
                                        class="img-raised rounded-circle img-fluid">
                                </div>
                                <h4 class="card-title">Kajal Pawar
                                    <br>
                                    <small class="card-description text-muted">Front-End Developer</small>
                                </h4>
                                <div class="card-body">
                                    <p class="card-description">Exploration is the engine that drives innovation. Innovation drives economic growth.
                                        </p>
                                </div>
                                <div class="card-footer justify-content-center">
                                    <a href="https://www.instagram.com/kajalpawar238/" target='_blank' class="btn btn-link btn-just-icon"><i
                                            class="fa fa-instagram"></i></a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="team-player">
                            <div class="card card-plain">
                                <div class="col-md-6 ml-auto mr-auto">
                                    <img src="{% static 'assets/img/faces/kshitij.jpg' %}" alt="Thumbnail Image"
                                        class="img-raised rounded-circle img-fluid">
                                </div>
                                <h4 class="card-title">Kshitij Sabale
                                    <br>
                                    <small class="card-description text-muted">Backend Developer</small>
                                </h4>
                                <div class="card-body">
                                    <p class="card-description">Innovation distinguishes between a leader and a follower.
                                        </p>
                                </div>
                                <div class="card-footer justify-content-center">
                                    <a href="https://www.instagram.com/sabalekshitij/" target='_blank' class="btn btn-link btn-just-icon"><i
                                            class="fa fa-instagram"></i></a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="team-player">
                            <div class="card card-plain">
                                <div class="col-md-6 ml-auto mr-auto">
                                    <img src="{% static 'assets/img/faces/teknath.jpg' %}" alt="Thumbnail Image"
                                        class="img-raised rounded-circle img-fluid">
                                </div>
                                <h4 class="card-title">Teknath Jha
                                    <br>
                                    <small class="card-description text-muted">Full-Stack Developer</small>
                                </h4>
                                <div class="card-body">
                                    <p class="card-description">Changes call for innovation, and innovation leads to progress.
                                        </p>
                                </div>
                                <div class="card-footer justify-content-center">
                                    <a href="https://www.instagram.com/teknath.jha/" target='_blank' class="btn btn-link btn-just-icon"><i
                                            class="fa fa-instagram"></i></a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="team-player">
                            <div class="card card-plain">
                                <div class="col-md-6 ml-auto mr-auto">
                                    <img src="{% static 'assets/img/faces/devang.jpg' %}" alt="Thumbnail Image"
                                        class="img-raised rounded-circle img-fluid">
                                </div>
                                <h4 class="card-title">Devang Kamble
                                    <br>
                                    <small class="card-description text-muted">Full-Stack Developer</small>
                                </h4>
                                <div class="card-body">
                                    <p class="card-description">Every once in a while, a new technology, an old problem, and a big idea turn into an innovation
                                        </p>
                                </div>
                                <div class="card-footer justify-content-center">
                                    <a href="https://www.instagram.com/devangkamble/" target='_blank' class="btn btn-link btn-just-icon"><i
                                            class="fa fa-instagram"></i></a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}